# Generated by Django 4.1.3 on 2022-11-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-is_completed", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.CharField(max_length=127),
        ),
    ]
