# Generated by Django 4.1.3 on 2022-11-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0002_alter_task_options_alter_tag_name_alter_task_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "-created_at"]},
        ),
    ]
